#FROM openjdk:11-stretch
FROM brownie_atelier_base:0.10

#LABELでメタ情報を入れることができる
#LABEL maintainer="Martijn Koster \"mak-docker@greenhills.co.uk\""
#LABEL repository="https://github.com/docker-solr/docker-solr"
LABEL maintainer="BrownieAtelier-app-test"

ARG NORMAL_USER
ARG GIT_REMOTE_REPOSITORY

# アプリ用ディレクトリ作成
WORKDIR /home/${NORMAL_USER}//BrownieAtelier

RUN git init
# azureの共有ファイルに保存する際、セキュリティで警告が出るため以下のコマンドで安全であるディレクトリであると設定する。
RUN git config --global --add safe.directory /home/${NORMAL_USER}/BrownieAtelier
# BrownieAtelierのリモートリポジトリを登録
RUN git remote add origin $GIT_REMOTE_REPOSITORY
# リモートリポジトリよりpullを実行し初回のソースを取得する。
#まだmasterじゃない、、、
RUN git pull origin develop

# アプリ内でpython仮想環境構築
WORKDIR /home/${NORMAL_USER}
RUN python3.9 -m venv .venv
RUN "." .venv/bin/activate
RUN .venv/bin/pip install --upgrade pip
# pythonライブラリ系インストール
RUN /home/${NORMAL_USER}/.venv/bin/pip install -r /home/${NORMAL_USER}/BrownieAtelier/app/requirements.txt


# pythonライブラリのインストール完了後、git pullした情報を抹消(容量節約)
WORKDIR /home/${NORMAL_USER}//BrownieAtelier
RUN rm -rf *; \
    rm -rf .git; \
    rm -rf .dockerignore; \
    rm -rf .gitignore; \
    rm -rf .vscode

# オーナー＆グループをOSユーザーに変更
WORKDIR /home/${NORMAL_USER}
RUN chown -R ${NORMAL_USER}:${NORMAL_USER} .

# コンテナ実行時のユーザーをOSユーザーへ変更
USER ${NORMAL_USER}