FROM ubuntu:20.04

#LABELでメタ情報を入れることができる
LABEL maintainer="BrownieAtelier-base-test"

# タイムゾーン設定
ENV TZ Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# リポジトリ一覧を更新、インストール済みのパッケージ更新
# 必要なアプリをインストール
RUN apt-get update
RUN apt update
RUN apt -y upgrade
RUN apt -y install build-essential libssl-dev wget firefox
#RUN apt -y install build-essential libssl-dev wget firefox libbz2-dev libdb-dev libreadline-dev libffi-dev libgdbm-dev liblzma-dev libncursesw5-dev libsqlite3-dev zlib1g-dev uuid-dev tk-dev

# Selenium用にgeckodriverを取得して配置。不要になったダウンロードファイル削除
RUN wget -P /usr/local/bin/ "https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz"
RUN tar -zxvf /usr/local/bin/geckodriver-v0.31.0-linux64.tar.gz -C /usr/local/bin
RUN rm /usr/local/bin/geckodriver-v0.31.0-linux64.tar.gz

# pythonまわりのインストール
#   参考サイト
#     【初心者向け】Ubuntuに最新のPythonをインストール
#      https://invisiblepotato.com/ubuntu05/
# RUN wget -P / "https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tar.xz"
# RUN tar Jxfv /Python-3.10.5.tar.xz -C /
# WORKDIR /Python-3.10.5
# RUN ./configure
# RUN make
# RUN make install
# WORKDIR /
# RUN rm /Python-3.10.5.tar.xz
# RUN rm -r /Python-3.10.5
# # /usr/bin/python3.8に関するリンクより優先されるため削除（OSデフォルトは変更禁止）
# RUN rm /usr/local/bin/python3
# RUN rm /usr/local/bin/python3-config

# ppaなどでインストールさせていた時の記録
#RUN apt -y install software-properties-common
#RUN add-apt-repository ppa:deadsnakes/ppa
#RUN apt -y install python3.10
#RUN apt -y install python3.10-venv
# RUN apt -y install python3-pip
# 完了後PPAの削除
# RUN add-apt-repository --remove ppa:deadsnakes/ppa

RUN apt -y install python3.9
RUN apt -y install python3.9-venv
#RUN apt -y install python3-pip
RUN apt -y install python3-selenium

# 更新時に使われたが、その後不要となったものの一括削除
# キャッシュされているがインストールされていないdebファイルを削除
# 不要なアプリを削除
RUN apt autoremove
RUN apt autoclean
RUN apt -y remove build-essential libssl-dev wget
#RUN apt -y remove build-essential libssl-dev wget firefox libbz2-dev libdb-dev libreadline-dev libffi-dev libgdbm-dev liblzma-dev libncursesw5-dev libsqlite3-dev zlib1g-dev uuid-dev tk-dev

# アプリ用ディレクトリ作成
WORKDIR /app

# ホストOSからアプリをコピー
COPY app/requirements.txt /app/

# アプリ内でpython仮想環境構築
ENV PYTHONPATH "/app:/app/.venv/bin/"
RUN python3.9 -m venv .venv
RUN "." /app/.venv/bin/activate
RUN /app/.venv/bin/pip install --upgrade pip
RUN ls -l /app/.venv/bin/
RUN /app/.venv/bin/pip install -r requirements.txt

ENTRYPOINT []
CMD []
